id: P55C83566
initial_creation_type: ocr
source_metadata:
  volumes:
    fc668b7c976f4ce899daffdc1a945c3f:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཡི་གེ་བརྒྱ་པ་ཞེས་བྱ་བའི་འགྲེལ་པ།
      total_pages: 1605
      volume_number: 57
